"""Complaint letter drafter — generates formal complaint letters with legal references."""

from __future__ import annotations

import random
import string
from datetime import datetime, timedelta, timezone

from src.models import Country, IssueType
from src.rights import get_rights

# ---------------------------------------------------------------------------
# Draft formal complaint letters.
#
# Templates are contextualised with the user's specific issue, the relevant
# legal framework, and a deadline for the company to respond.
#
# In v0.1 all drafting is template-based with no LLM call. This keeps the
# server fast, deterministic, and dependency-free. A future version could
# offer an LLM-enhanced mode.
# ---------------------------------------------------------------------------


def _generate_reference() -> str:
    """Generate a random complaint reference number."""
    prefix = "CC"
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d")
    suffix = "".join(random.choices(string.ascii_uppercase + string.digits, k=6))
    return f"{prefix}-{timestamp}-{suffix}"


def _format_date(days_from_now: int = 14) -> str:
    """Return a formatted date N days from now."""
    return (datetime.now(timezone.utc) + timedelta(days=days_from_now)).strftime("%B %d, %Y")


def _deadline_text(deadline_str: str | None) -> str:
    """Extract a readable deadline from a rights entry."""
    if deadline_str:
        return f"Legal deadline to pursue this claim: {deadline_str}"
    return "Please respond within 14 calendar days."


def draft_complaint(
    company: str,
    issue: str,
    amount: str | None = None,
    outcome: str | None = None,
    issue_type: IssueType | None = None,
    country: Country | None = None,
) -> str:
    """Generate a formal complaint letter.

    Args:
        company: Company or entity being complained about.
        issue: Description of the issue.
        amount: Amount claimed (e.g. '$350' or 'repair cost').
        outcome: Desired resolution.
        issue_type: Type of issue (for legal references).
        country: Country (for legal references).

    Returns:
        Formatted complaint letter as a string.
    """
    ref = _generate_reference()
    today = datetime.now(timezone.utc).strftime("%B %d, %Y")
    response_date = _format_date(14)

    # Try to get statutory right info for context
    right_info = None
    if issue_type is not None and country is not None:
        right_info = get_rights(issue_type, country)

    amount_line = f"\nAmount claimed: {amount}" if amount else ""
    outcome_line = f"\nDesired resolution: {outcome}" if outcome else ""

    rights_section = ""
    if right_info:
        rights_section = f"""
LEGAL BASIS

Under {right_info.reference}:

{right_info.summary}

{_deadline_text(right_info.deadline)}
"""

    letter = f"""\
COMPLAINT REFERENCE: {ref}
DATE: {today}

FORMAL COMPLAINT

To:
{company}
Customer Complaints Department

RE: Formal Complaint{amount_line}{outcome_line}

Dear Sir or Madam,

I am writing to formally raise a complaint regarding the following matter:

{issue}

I believe this constitutes a breach of my consumer rights and the terms
under which the product or service was provided.{rights_section}
DESIRED RESOLUTION

I am requesting that you resolve this matter promptly. Specifically:
{outcome or "I expect a full refund and/or corrective action."}

RESPONSE DEADLINE

Please provide a full written response by {response_date} (14 calendar
days from the date of this letter). If I do not receive a satisfactory
response by that date, I will escalate this matter to the appropriate
regulatory body or ombudsman without further notice.

Please direct all correspondence regarding this complaint to the address
above, quoting reference {ref}.

Yours faithfully,

[Your Name]
[Your Address]
[Your Email]
[Your Phone Number]

---
This letter was generated by Complaint Copilot. Reference: {ref}
"""

    return letter.strip()
