"""Command-line interface.

    commentary demo                      # offline scripted match, English
    commentary demo --language Spanish --speak
    commentary discover --provider espn --sport soccer --league eng.1
    commentary live --provider espn --sport basketball --league nba \
        --match 401585601 --language French --style hype --speak

If an Anthropic API key is present, commentary is generated by Claude in the
chosen language; otherwise it falls back to the offline template engine.
"""

from __future__ import annotations

import argparse
import sys
from typing import Optional

from .config import Settings
from .engine import ClaudeEngine, TemplateEngine
from .providers import create_provider
from .runner import Runner
from .styles import STYLES
from .tts import make_speaker


def _build_engine(settings: Settings, language: str, style: str, force_offline: bool):
    if not force_offline and settings.has_anthropic:
        try:
            return ClaudeEngine(
                api_key=settings.anthropic_api_key,
                model=settings.anthropic_model,
                language=language,
                style=style,
            ), "claude"
        except Exception as exc:  # missing SDK, etc.
            print(f"[warn] Claude engine unavailable ({exc}); using offline engine.",
                  file=sys.stderr)
    return TemplateEngine(language=language, style=style), "template"


def _provider_kwargs(args) -> dict:
    kw = {}
    if getattr(args, "sport", None):
        kw["sport"] = args.sport
    if getattr(args, "league", None):
        kw["league"] = args.league
    if getattr(args, "speed", None):
        kw["speed"] = args.speed
    return kw


def cmd_discover(args, settings: Settings) -> int:
    provider = create_provider(args.provider, **_provider_kwargs(args))
    try:
        results = provider.discover(args.query or "")
    except NotImplementedError as exc:
        print(exc, file=sys.stderr)
        return 2
    if not results:
        print("No matches found.")
        return 0
    for s in results:
        flag = {"in": "● LIVE", "final": "✓ FT", "scheduled": "· upcoming"}.get(
            s.status, s.status
        )
        clock = f" {s.clock}" if s.clock else ""
        print(f"{s.match_id:>12}  {flag:<10}{clock:<6}  {s.description}  [{s.league}]")
    return 0


def _run(args, settings: Settings, match_id: str, provider_name: str) -> int:
    provider = create_provider(provider_name, **_provider_kwargs(args))
    engine, kind = _build_engine(settings, args.language, args.style, args.offline)
    speaker = make_speaker(enabled=args.speak, language=args.language)

    print(f"# provider={provider.name} engine={kind} language={args.language} "
          f"style={args.style} match={match_id}", file=sys.stderr)

    last_score = {"v": None}

    def on_state(state):
        if state.scoreline() != last_score["v"]:
            last_score["v"] = state.scoreline()
            print(f"\n=== {state.home.name} vs {state.away.name} — "
                  f"{state.headline()} ===", file=sys.stderr)

    runner = Runner(provider=provider, engine=engine, speaker=speaker)
    runner.run(match_id, max_ticks=args.max_ticks, on_state=on_state)
    return 0


def cmd_live(args, settings: Settings) -> int:
    return _run(args, settings, args.match, args.provider)


def cmd_demo(args, settings: Settings) -> int:
    args.provider = "simulated"
    args.speed = args.speed or 30.0
    # The simulated provider always uses match id "sim-1".
    return _run(args, settings, "sim-1", "simulated")


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="commentary",
        description="Live, multilingual sports commentary from any match feed.",
    )
    sub = p.add_subparsers(dest="command", required=True)

    def add_common(sp):
        sp.add_argument("--language", default="English",
                        help="Commentary language, e.g. English, Spanish, Japanese.")
        sp.add_argument("--style", default="play-by-play", choices=sorted(STYLES),
                        help="Commentator persona.")
        sp.add_argument("--speak", action="store_true",
                        help="Speak the commentary aloud (needs gTTS or pyttsx3).")
        sp.add_argument("--offline", action="store_true",
                        help="Force the offline template engine even if a key exists.")
        sp.add_argument("--max-ticks", type=int, default=None,
                        help="Stop after N polls (useful for testing).")

    # demo
    d = sub.add_parser("demo", help="Run an offline scripted match end to end.")
    add_common(d)
    d.add_argument("--speed", type=float, default=30.0,
                   help="Simulated minutes per real second (higher = faster).")
    d.set_defaults(func=cmd_demo)

    # live
    lv = sub.add_parser("live", help="Commentate a real live match.")
    add_common(lv)
    lv.add_argument("--provider", default="espn",
                    help="Provider name (espn, football-data, ...).")
    lv.add_argument("--match", required=True, help="Match/event id from the provider.")
    lv.add_argument("--sport", default="soccer", help="ESPN sport slug.")
    lv.add_argument("--league", default="eng.1", help="ESPN league slug.")
    lv.set_defaults(func=cmd_live)

    # discover
    ds = sub.add_parser("discover", help="List matches available from a provider.")
    ds.add_argument("--provider", default="espn")
    ds.add_argument("--sport", default="soccer")
    ds.add_argument("--league", default="eng.1")
    ds.add_argument("--query", default="", help="Optional text filter.")
    ds.set_defaults(func=cmd_discover)

    return p


def main(argv: Optional[list] = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    settings = Settings.load()
    return args.func(args, settings)


if __name__ == "__main__":
    raise SystemExit(main())
