"""Roast card formatting — turns RoastCard data into shareable text output."""

from __future__ import annotations

import os
import textwrap
from datetime import datetime
from typing import List, Optional

from src.models import Roast, RoastCard


CARD_WIDTH = 72


def _rule(char: str = "─") -> str:
    return char * CARD_WIDTH


def _center(text: str, width: int = CARD_WIDTH) -> str:
    """Center text within the card width, stripped."""
    stripped = text.strip()
    if len(stripped) >= width:
        return stripped
    left = (width - len(stripped)) // 2
    return " " * left + stripped


def _wrap(text: str, width: int = CARD_WIDTH - 4) -> str:
    """Wrap text for the card interior."""
    return "\n".join(textwrap.fill(line, width=width) for line in text.split("\n"))


def format_card(card: RoastCard, filepath: Optional[str] = None) -> str:
    """Format a RoastCard into a shareable text block.

    Args:
        card: The populated roast card.
        filepath: Optional path to write the card to a file.

    Returns:
        The formatted card as a string.
    """
    lines: List[str] = []

    # ── Header ──
    lines.append(_rule("█"))
    lines.append("")
    lines.append(_center(f"🔥 {card.title} 🔥"))
    lines.append(_center(f"Tone: {card.tone.name.upper()}  |  Intensity: {card.tone.vibe}"))
    lines.append("")
    lines.append(_rule("▒"))

    # ── Tone description ──
    lines.append("")
    lines.append(_wrap(f"🎭 {card.tone.description}"))
    lines.append("")

    # ── Group setting ──
    if card.group.setting:
        lines.append(_wrap(f"📍 {card.group.setting}"))
        lines.append("")

    # ── Group roast ──
    if card.group_roast:
        lines.append(_rule("▒"))
        lines.append("")
        lines.append(_center("📸 GROUP ROAST"))
        lines.append("")
        lines.append(_wrap(f"  {card.group_roast}"))
        lines.append("")

    # ── Individual roasts ──
    lines.append(_rule("▒"))
    lines.append("")
    lines.append(_center("🎯 INDIVIDUAL ROASTS"))
    lines.append("")

    for i, roast in enumerate(card.roasts, 1):
        person = roast.person
        name_tag = person.name or f"Person {i}"

        lines.append(f"  ┌─ {name_tag}")
        lines.append(f"  │  Expression: {person.expression.value}")
        lines.append(f"  │  Outfit: {person.outfit.value}")
        lines.append(f"  │  Vibe: {person.vibe.value}")
        lines.append(f"  │  Position: {person.arrangement.value}")
        lines.append("  ├─")

        for line in roast.lines:
            wrapped = _wrap(f"  • {line}", width=CARD_WIDTH - 6)
            for wl in wrapped.split("\n"):
                lines.append(f"  │  {wl}")

        lines.append(f"  │")
        lines.append(f"  └─ 💀 {roast.final_verdict}")
        lines.append("")

    # ── Footer ──
    lines.append(_rule("▒"))
    if card.footer:
        lines.append("")
        lines.append(_center(card.footer))
        lines.append("")

    lines.append(_center(f"Generated by Roster — {datetime.now().strftime('%Y-%m-%d %H:%M')}"))
    lines.append(_rule("█"))

    output = "\n".join(lines)

    # Write to file if requested
    if filepath:
        os.makedirs(os.path.dirname(filepath) or ".", exist_ok=True)
        with open(filepath, "w") as f:
            f.write(output)

    return output