"""Format PR review results as structured markdown reports."""

from __future__ import annotations

from src.models import (
    Issue,
    IssueSeverity,
    Patch,
    PRInfo,
    ReviewCategory,
    ReviewReport,
    TestResult,
)


def format_report(report: ReviewReport) -> str:
    """Format the complete review report as markdown.

    Returns a structured markdown string suitable for posting as a PR comment.
    """
    sections: list[str] = []

    # Header
    sections.append(
        f"# PR Auto-Pilot Review — {report.pr_info.repo_owner}/{report.pr_info.repo_name}#{report.pr_info.pr_number}\n"
    )

    # Summary
    sections.append("## Summary")
    sections.append(report.summary if report.summary else _generate_summary(report))

    # Confidence
    confidence_pct = round(report.confidence * 100)
    bar = _confidence_bar(report.confidence)
    sections.append(f"\n**Confidence:** {confidence_pct}% {bar}")
    sections.append(f"**Iterations:** {report.iteration_count + 1}")
    sections.append(f"**Files changed:** {len(report.files_changed)}")
    sections.append(f"**Issues found:** {len(report.issues)}")

    if report.test_results:
        tr = report.test_results
        test_icon = "✅" if tr.passed else "❌"
        sections.append(
            f"**Tests:** {test_icon} {tr.passed_count}/{tr.total} passed "
            f"({tr.duration_seconds:.1f}s)"
        )

    # Issues by severity
    sections.append("\n## Issues Found")
    if not report.issues:
        sections.append("\nNo issues detected. The code looks clean. ✨")
    else:
        _format_issues_table(sections, report.issues)

    # Patches applied
    if report.patches:
        sections.append("\n## Patches Applied")
        applied = [p for p in report.patches if p.applied]
        failed = [p for p in report.patches if not p.applied]
        sections.append(
            f"\n- **{len(applied)}** patches applied successfully"
        )
        if failed:
            sections.append(f"- **{len(failed)}** patches failed to apply")
            for p in failed:
                sections.append(f"  - `{p.file}`: {p.error}")

        for p in applied:
            sections.append(f"\n### Patch: `{p.file}`")
            if p.diff:
                sections.append("```diff")
                sections.append(p.diff[:500])  # Truncate long diffs
                sections.append("```")

    # Test results
    if report.test_results:
        sections.append("\n## Test Results")
        tr = report.test_results
        status = "✅ PASSED" if tr.passed else "❌ FAILED"
        sections.append(f"\n**Status:** {status}")
        sections.append(f"**Duration:** {tr.duration_seconds:.1f}s")
        sections.append(f"**Total:** {tr.total} | **Passed:** {tr.passed_count} | **Failed:** {tr.failed_count}")

        if tr.errors:
            sections.append("\n### Errors")
            for err in tr.errors[:10]:
                sections.append(f"\n```\n{err}\n```")

        if not tr.passed and tr.output:
            sections.append("\n### Output")
            sections.append(f"\n```\n{tr.output[:2000]}\n```")

    # Footer
    sections.append(
        "\n---\n*Generated by [PR Auto-Pilot](https://github.com/nousresearch/pr-auto-pilot)*"
    )

    return "\n".join(sections)


def format_short_summary(report: ReviewReport) -> str:
    """Format a brief one-liner summary."""
    critical = len([i for i in report.issues if i.severity == IssueSeverity.critical])
    major = len([i for i in report.issues if i.severity == IssueSeverity.major])
    minor = len([i for i in report.issues if i.severity == IssueSeverity.minor])
    suggestion = len([i for i in report.issues if i.severity == IssueSeverity.suggestion])

    issues_str = (
        f"{len(report.issues)} issues "
        f"({critical} critical, {major} major, {minor} minor, {suggestion} suggestions)"
    )

    test_str = ""
    if report.test_results:
        icon = "✅" if report.test_results.passed else "❌"
        test_str = f" | Tests: {icon} {report.test_results.passed_count}/{report.test_results.total}"

    confidence_str = f"{round(report.confidence * 100)}% confidence"

    return f"PR Auto-Pilot: {issues_str} | {confidence_str}{test_str}"


def _generate_summary(report: ReviewReport) -> str:
    """Generate a brief summary from issues."""
    if not report.issues:
        return "This PR looks clean. No issues were found during the review."

    critical_count = len([i for i in report.issues if i.severity == IssueSeverity.critical])
    major_count = len([i for i in report.issues if i.severity == IssueSeverity.major])

    parts: list[str] = []
    if critical_count > 0:
        parts.append(f"Found **{critical_count} critical** issue(s) that should be addressed before merging.")
    if major_count > 0:
        parts.append(f"Found **{major_count} major** issue(s) that should be reviewed.")
    if not parts:
        parts.append(
            f"Found **{len(report.issues)}** issue(s), mostly minor suggestions."
        )

    return " ".join(parts)


def _format_issues_table(sections: list[str], issues: list[Issue]) -> None:
    """Format issues grouped by severity."""
    severity_order = [
        IssueSeverity.critical,
        IssueSeverity.major,
        IssueSeverity.minor,
        IssueSeverity.suggestion,
    ]

    for severity in severity_order:
        sev_issues = [i for i in issues if i.severity == severity]
        if not sev_issues:
            continue

        label_map = {
            IssueSeverity.critical: "🔴 Critical",
            IssueSeverity.major: "🟠 Major",
            IssueSeverity.minor: "🟡 Minor",
            IssueSeverity.suggestion: "🔵 Suggestion",
        }

        sections.append(f"\n### {label_map[severity]}")
        sections.append("")
        sections.append("| # | File | Lines | Category | Issue | Confidence |")
        sections.append("|---|---|---|---|---|---|")

        for idx, issue in enumerate(sev_issues, 1):
            lines = f"{issue.line_start}-{issue.line_end}" if issue.line_end > issue.line_start else str(issue.line_start)
            confidence_pct = f"{round(issue.confidence * 100)}%"
            sections.append(
                f"| {idx} | `{issue.file}` | L{lines} | {issue.category.value} | "
                f"{issue.title} | {confidence_pct} |"
            )

        # Details for each issue
        for idx, issue in enumerate(sev_issues, 1):
            sections.append(f"\n**{idx}. {issue.title}** (`{issue.file}`:{issue.line_start})")
            sections.append(f"   - **Category:** {issue.category.value}")
            sections.append(f"   - **Confidence:** {round(issue.confidence * 100)}%")
            sections.append(f"   - **Description:** {issue.description}")
            if issue.suggested_fix:
                sections.append("   - **Suggested fix:**")
                sections.append("     ```")
                sections.append(f"     {issue.suggested_fix[:300]}")
                sections.append("     ```")


def _confidence_bar(confidence: float) -> str:
    """Render a simple ASCII confidence bar."""
    filled = round(confidence * 10)
    empty = 10 - filled
    bar = "█" * filled + "░" * empty
    return f"[{bar}]"