"""Pydantic models for ARGUS data types."""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class SourceType(str, Enum):
    WEB = "web"
    ARXIV = "arxiv"
    HN = "hackernews"
    BLOG = "blog"


class SearchResult(BaseModel):
    """A single search result from any source."""

    title: str
    url: str
    snippet: str
    source: SourceType
    source_name: str = Field(default="", description="Display name of the source")
    published: Optional[str] = None
    relevance_score: float = Field(default=0.0, ge=0.0, le=1.0)


class ExtractedContent(BaseModel):
    """Full text extracted from a crawled source."""

    url: str
    title: str
    content: str
    source: SourceType
    word_count: int = 0


class SubQuestion(BaseModel):
    """A sub-question generated by the planner."""

    question: str
    intent: str = ""
    priority: int = Field(default=0, ge=0)


class Finding(BaseModel):
    """A discrete finding extracted from a source."""

    statement: str
    url: str
    source_type: SourceType
    confidence: float = Field(default=0.5, ge=0.0, le=1.0)


class CrossReferenceResult(BaseModel):
    """Output of cross-referencing findings across sources."""

    consensus_points: list[str] = []
    contradictions: list[dict] = []
    gaps: list[str] = []
    cross_referenced_sources: int = 0


class ReportSection(BaseModel):
    """A section of the final report."""

    heading: str
    body: str
    citations: list[str] = []


class ResearchReport(BaseModel):
    """The final research report."""

    title: str
    query: str
    sub_questions: list[SubQuestion] = []
    executive_summary: str = ""
    sections: list[ReportSection] = []
    cross_reference: CrossReferenceResult = Field(default_factory=CrossReferenceResult)
    sources_count: int = 0
    generated_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat())
    citations: list[str] = []