"""Report formatter — produces markdown output."""

from __future__ import annotations

from src.models import ResearchReport, SourceType


def format_report(report: ResearchReport) -> str:
    """Format a ResearchReport as well-structured markdown."""
    lines: list[str] = []

    # Title
    lines.append(f"# {report.title}")
    lines.append("")
    lines.append(f"*Generated at: {report.generated_at}*")
    lines.append("")
    lines.append(f"**Sources reviewed:** {report.sources_count}")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Query
    lines.append("## Research Query")
    lines.append("")
    lines.append(f"> {report.query}")
    lines.append("")

    # Sub-questions
    if report.sub_questions:
        lines.append("## Sub-Questions Investigated")
        lines.append("")
        for sq in report.sub_questions:
            icon = "🔍"
            lines.append(f"- {icon} **{sq.question}**")
            if sq.intent:
                lines.append(f"  - *Intent:* {sq.intent}")
        lines.append("")

    # Executive summary
    lines.append("## Executive Summary")
    lines.append("")
    lines.append(report.executive_summary)
    lines.append("")

    # Report sections
    for section in report.sections:
        lines.append(f"## {section.heading}")
        lines.append("")
        lines.append(section.body)
        lines.append("")
        if section.citations:
            lines.append("*See: " + ", ".join(section.citations) + "*")
            lines.append("")

    # Cross-reference summary
    lines.append("## Cross-Reference Analysis")
    lines.append("")
    cr = report.cross_reference
    lines.append(f"- **Sources cross-referenced:** {cr.cross_referenced_sources}")
    lines.append(f"- **Consensus points found:** {len(cr.consensus_points)}")
    lines.append(f"- **Contradictions detected:** {len(cr.contradictions)}")
    lines.append(f"- **Research gaps identified:** {len(cr.gaps)}")
    lines.append("")

    # Full citations
    lines.append("## Citations")
    lines.append("")
    for c in report.citations:
        lines.append(f"- {c}")
    lines.append("")

    # Footer
    lines.append("---")
    lines.append("*Report generated by ARGUS — Deep Research Agent*")

    return "\n".join(lines)